### PR TITLE
Update sandboxes to use vite and typescript

### PR DESCRIPTION
**Pull request by ChristianMurphy**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [x] If applicable, I’ve added docs and tests

### Description of changes

the native dependencies in parcel no longer work in browser sandboxes like stackblitz

https://stackblitz.com/github/ChristianMurphy/.github-rehype/tree/migrate-parcel-to-vite/sandbox-templates/rehype-debug
https://stackblitz.com/github/ChristianMurphy/.github-rehype/tree/migrate-parcel-to-vite/sandbox-templates/rehype-dom-debug

### CODE REVIEW

**Comment by remcohaszing** [comment]
Is there a particular reason to switch to TypeScript? I'm not against it, but most of the unified ecosystem uses JavaScript.

**Comment by ChristianMurphy** [comment]
This is mirroring https://github.com/remarkjs/.github/pull/9
The reason being

> also run sandboxes through typescript to catch potential issues with plugin compatibility and options.

---

If your question is more towards TS syntax vs JSDoc syntax.
The reason is to more closely match what vite has setup by default.
These are not packages nor are they published to npm, they are sandboxes designed to roughly match what an average developer setup may look like.
If we want to push JSDoc for that as well, I'm happy to, but that may diverge a bit from a usual vite setup.

**Review by remcohaszing — APPROVED** [review]

**Comment by remcohaszing** [comment]
Personally I'm all for TS syntax, especially for code that's not run directly in Node.js.

**Comment by ChristianMurphy** [comment]
Merging this in, as the current sandboxes are broken.
@rehypejs/maintainers if you have further thoughts and suggestions, feel free to add them, happy to discuss more and potentially add follow up PRs.

**Pull request merged**
